# -*- coding: utf-8 -*-
"""Introdução a data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdgX4ncpWcKmMTFVw0qp7ac5a8L4Nrnl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

notas = pd.read_csv('ratings.csv')
notas.head()

notas.shape

notas.columns = ["usuarioID", "filmeID","nota", "momento"]
notas.head()

notas['rating'] .unique()

notas['rating'] .value_counts()

print(notas['nota'].mean() )
print(notas['nota'].median() )

notas.rating.describe()

notas.rating.plot(kind='hist')

import seaborn as sns

sns.boxplot(notas.nota)
#metades da nota são entre 3 e 4

"""#Olhando os filmes"""

filmes = pd.read_csv("movies.csv")
filmes.columns = ["filmeID", "titulo", "generos"]
filmes.head()

"""#Analisando algumas notas especificas por filme

"""

notas.query("filmeID==1").nota.mean()

notas.query("filmeID==2").nota.mean()

medias_por_filme = notas.groupby("filmeID").mean()["nota"]
medias_por_filme.head()

medias_por_filme.plot(kind="hist")

medias_por_filme.describe()

sns.boxplot(medias_por_filme)

sns.distplot(medias_por_filme, bins = 10)

import matplotlib.pyplot as plt
plt.hist(medias_por_filme)
plt.title("Histograma das medias dos filmes")

